import pathlib
import random
from typing import List, Dict, Any, Set, Tuple, Optional

import pandas as pd
import flowio

# --- Configuration Constants ---
# IMPORTANT: User should verify these paths and names
# Path to the CSV file generated by clean_anudc.py
INPUT_FILTERED_METADATA_CSV: pathlib.Path = pathlib.Path(
    "/g/data/eu59/data_flowmop/ANUDC_16/filtered_anu_dc_metadata.csv"
)
# Base directory where FCS files are stored
FCS_FILES_BASE_DIR: pathlib.Path = pathlib.Path(
    "/g/data/eu59/data_flowmop/ANUDC_16/FCS_files/cells_panel"
)
# Output path for the CSV with selected and processed columns
OUTPUT_SELECTED_COLUMNS_CSV: pathlib.Path = pathlib.Path(
    "/g/data/eu59/data_flowmop/ANUDC_16/selected_metadata_columns.csv"
)
# Output path for the CSV with marker names from sampled FCS files
OUTPUT_MARKER_NAMES_CSV: pathlib.Path = pathlib.Path(
    "/g/data/eu59/data_flowmop/ANUDC_16/sampled_marker_names.csv"
)

# Column names
FILENAME_COLUMN_IN_METADATA: str = "filename"
USER_SPECIFIED_COLUMN_TO_EXTRACT: str = "day" # The column to process and extract
PROCESSED_USER_COLUMN_NAME: str = f"{USER_SPECIFIED_COLUMN_TO_EXTRACT}_numeric" # Name for the cleaned column

NUMBER_OF_FCS_FILES_TO_SAMPLE: int = 10


def extract_and_save_selected_columns(
    input_csv_path: pathlib.Path,
    output_csv_path: pathlib.Path,
    filename_col: str,
    user_col_to_extract: str,
    processed_user_col_name: str,
) -> pd.DataFrame:
    """
    Reads a metadata CSV, processes a user-specified column, and saves selected columns.

    The user-specified column (e.g., 'day') will have non-numeric characters
    removed and then be converted to an integer type.

    Args:
        input_csv_path: Path to the input metadata CSV file.
        output_csv_path: Path where the filtered metadata CSV will be saved.
        filename_col: Name of the column containing filenames.
        user_col_to_extract: Name of the user-specified column to process.
        processed_user_col_name: The name for the new column after processing.

    Returns:
        A pandas DataFrame containing all original columns, plus the processed
        user column. This DataFrame can be used for further operations like sampling.

    Raises:
        FileNotFoundError: If the input CSV file does not exist.
        KeyError: If required columns are not found in the CSV.
        ValueError: If processing the user-specified column results in values
                    that cannot be converted to integers (e.g., empty strings
                    after stripping non-digits).
    """
    if not input_csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {input_csv_path}")

    try:
        metadata_df = pd.read_csv(input_csv_path)
    except Exception as e:
        print(f"Error reading metadata CSV {input_csv_path}: {e}")
        raise

    if filename_col not in metadata_df.columns:
        msg = f"Filename column '{filename_col}' not found in {input_csv_path}."
        raise KeyError(msg)
    if user_col_to_extract not in metadata_df.columns:
        msg = (
            f"User-specified column '{user_col_to_extract}' not found "
            f"in {input_csv_path}."
        )
        raise KeyError(msg)

    # Process the user-specified column
    # Convert to string, remove non-digits, then attempt to convert to numeric
    cleaned_series = (
        metadata_df[user_col_to_extract]
        .astype(str)
        .str.replace(r"\D+", "", regex=True)  # Removed extra backslash
    )

    # Replace empty strings (which result if the original had no digits) with NaN
    # so pd.to_numeric can handle them
    cleaned_series_with_na = cleaned_series.replace("", pd.NA)
    numeric_series = pd.to_numeric(cleaned_series_with_na, errors="coerce")

    # Check for conversion errors (NaNs)
    if numeric_series.isnull().any():
        problematic_indices = numeric_series[numeric_series.isnull()].index
        problematic_original_values = metadata_df[user_col_to_extract][
            problematic_indices
        ].tolist()
        msg = (
            f"Error converting column '{user_col_to_extract}' to numeric. "
            f"Problematic original values: {problematic_original_values}. "
            "These values resulted in non-numeric entries after stripping non-digits."
        )
        raise ValueError(msg)

    metadata_df[processed_user_col_name] = numeric_series.astype(int)

    # Select and save the specified columns
    output_df = metadata_df[[filename_col, processed_user_col_name]].copy()

    try:
        output_csv_path.parent.mkdir(parents=True, exist_ok=True)
        output_df.to_csv(output_csv_path, index=False)
        print(f"Selected columns saved to: {output_csv_path}")
    except Exception as e:
        print(f"Error saving selected columns CSV to {output_csv_path}: {e}")
        raise
    
    # Return the full dataframe with the new processed column for sampling
    return metadata_df


def sample_fcs_extract_validate_markers(
    metadata_df: pd.DataFrame,
    fcs_base_dir: pathlib.Path,
    filename_col: str,
    num_samples: int,
    output_csv_path: pathlib.Path,
) -> None:
    """
    Samples FCS files, extracts marker names, validates their consistency,
    and saves them to a CSV.

    Args:
        metadata_df: DataFrame containing filenames (must include 'filename_col').
        fcs_base_dir: Base directory where FCS files are located.
        filename_col: Name of the column in metadata_df with FCS filenames.
        num_samples: Number of FCS files to randomly sample.
        output_csv_path: Path to save the CSV of marker names.

    Raises:
        FileNotFoundError: If an FCS file path does not exist.
        ValueError: If no FCS files are available for sampling, or if
                    marker names are inconsistent across sampled files.
        Exception: For other errors during FCS file processing.
    """
    if filename_col not in metadata_df.columns:
        raise KeyError(f"Filename column '{filename_col}' not in DataFrame.")

    all_filenames = metadata_df[filename_col].tolist()
    if not all_filenames:
        raise ValueError("No FCS filenames available in the provided metadata to sample from.")

    if len(all_filenames) < num_samples:
        print(
            f"Warning: Requested {num_samples} samples, but only "
            f"{len(all_filenames)} files are available. Using all available files."
        )
        sampled_filenames = all_filenames
    else:
        sampled_filenames = random.sample(all_filenames, num_samples)
    
    if not sampled_filenames:
        print("No files were sampled. Marker CSV will not be generated.")
        return

    print(f"Selected {len(sampled_filenames)} files for marker extraction: {sampled_filenames}")

    marker_data: List[Dict[str, Any]] = []
    all_marker_sets: List[Tuple[str, ...]] = []
    first_marker_set: Optional[Tuple[str, ...]] = None

    for i, fname in enumerate(sampled_filenames):
        fcs_file_path = fcs_base_dir / fname
        if not fcs_file_path.is_file():
            # Try with .fcs if not found directly (clean_anudc removes spaces but keeps suffix)
            if not fcs_file_path.with_suffix(fcs_file_path.suffix + '.fcs').is_file() and not fcs_file_path.name.lower().endswith('.fcs'):
                 fcs_file_path_attempt = fcs_base_dir / (fname + ".fcs") # common if original filename had no suffix in CSV
                 if not fcs_file_path_attempt.is_file():
                    raise FileNotFoundError(
                        f"FCS file not found: {fcs_file_path} or {fcs_file_path_attempt}"
                    )
                 fcs_file_path = fcs_file_path_attempt
            elif not fcs_file_path.is_file() and fcs_file_path.with_suffix(fcs_file_path.suffix + '.fcs').is_file():
                 fcs_file_path = fcs_file_path.with_suffix(fcs_file_path.suffix + '.fcs')


        print(f"Processing file ({i+1}/{len(sampled_filenames)}): {fcs_file_path}")
        try:
            fd = flowio.FlowData(str(fcs_file_path))
            
            # Extract PnN labels by iterating through $P<n>N keywords in fd.text
            num_channels = fd.channel_count
            pnn_labels_list: List[str] = []
            for channel_idx in range(1, num_channels + 1):
                marker_key = f'$P{channel_idx}N'
                if marker_key in fd.text:
                    pnn_labels_list.append(fd.text[marker_key])
                else:
                    # Fallback if a PnN keyword is missing for a channel
                    pnn_labels_list.append(f"MISSING_P{channel_idx}N_LABEL")
                    print(
                        f"Warning: Marker key {marker_key} not found in FCS file "
                        f"{fname} (path: {fcs_file_path}). Using placeholder."
                    )

            current_markers: Tuple[str, ...] = tuple(pnn_labels_list)
            all_marker_sets.append(current_markers)

            if first_marker_set is None:
                first_marker_set = current_markers
            elif current_markers != first_marker_set:
                # For a more detailed error, could collect all differing ones
                error_msg = (
                    f"Marker inconsistency found! File '{fname}' markers "
                    f"{current_markers} do not match first sampled file's markers "
                    f"{first_marker_set}."
                )
                # Find all distinct marker sets for better error reporting
                distinct_marker_sets: Dict[Tuple[str, ...], List[str]] = {}
                for f, m_set in zip(sampled_filenames[:i+1], all_marker_sets):
                    if m_set not in distinct_marker_sets:
                        distinct_marker_sets[m_set] = []
                    distinct_marker_sets[m_set].append(f)
                
                if len(distinct_marker_sets) > 1:
                    error_details = "\\n".join(
                        [f"  Markers: {m_set} found in files: {files}" for m_set, files in distinct_marker_sets.items()]
                    )
                    error_msg = (
                        "Marker sets are not consistent across all sampled FCS files.\\n"
                        f"Details of differing sets:\\n{error_details}"
                    )
                raise ValueError(error_msg)

            # Store for CSV: filename and individual markers
            row_data: Dict[str, Any] = {filename_col: fname}
            for idx, marker_name in enumerate(current_markers):
                row_data[f"marker_{idx+1}"] = marker_name
            marker_data.append(row_data)

        except Exception as e:
            print(f"Error processing FCS file {fcs_file_path}: {e}")
            raise

    if not marker_data:
        print("No marker data extracted. CSV will not be generated.")
        return

    # If validation passed (or only one file sampled), save to CSV
    marker_df = pd.DataFrame(marker_data)
    try:
        output_csv_path.parent.mkdir(parents=True, exist_ok=True)
        marker_df.to_csv(output_csv_path, index=False)
        print(f"Marker names saved to: {output_csv_path}")
    except Exception as e:
        print(f"Error saving marker names CSV to {output_csv_path}: {e}")
        raise


def main() -> None:
    """
    Main function to orchestrate the data extraction and processing.
    """
    print("Starting data extraction process...")
    try:
        # Ensure output directories exist (though functions also do this)
        INPUT_FILTERED_METADATA_CSV.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_SELECTED_COLUMNS_CSV.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_MARKER_NAMES_CSV.parent.mkdir(parents=True, exist_ok=True)
        FCS_FILES_BASE_DIR.mkdir(parents=True, exist_ok=True) # Ensure base FCS dir for script to run if empty

        print(f"Step 1: Processing metadata from {INPUT_FILTERED_METADATA_CSV}")
        full_metadata_df = extract_and_save_selected_columns(
            input_csv_path=INPUT_FILTERED_METADATA_CSV,
            output_csv_path=OUTPUT_SELECTED_COLUMNS_CSV,
            filename_col=FILENAME_COLUMN_IN_METADATA,
            user_col_to_extract=USER_SPECIFIED_COLUMN_TO_EXTRACT,
            processed_user_col_name=PROCESSED_USER_COLUMN_NAME,
        )
        print("\\nStep 2: Sampling FCS files and extracting/validating marker names.")
        sample_fcs_extract_validate_markers(
            metadata_df=full_metadata_df, # Use the df returned, it has all filenames
            fcs_base_dir=FCS_FILES_BASE_DIR,
            filename_col=FILENAME_COLUMN_IN_METADATA,
            num_samples=NUMBER_OF_FCS_FILES_TO_SAMPLE,
            output_csv_path=OUTPUT_MARKER_NAMES_CSV,
        )
        print("\\nProcess completed successfully.")

    except FileNotFoundError as e:
        print(f"Process failed: A required file or directory was not found. Details: {e}")
    except KeyError as e:
        print(f"Process failed: A required column was not found. Details: {e}")
    except ValueError as e:
        print(f"Process failed: Data validation error. Details: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during the process: {e}")


if __name__ == "__main__":
    main() 